### ISSUE TITLE
DX11 / x64 support?

### ISSUE THREAD

**Issue by IrealiTY** [Soreepeong/DPSViewer#1]
Any plans for that? It's a really amazing tool for DX9 player already

**Comment by Soreepeong** [comment]
I already got hooking the x64 version working, but it's just that I didn't figure out about the usage of DX11 yet. I'm going to try adding support for DX11 after a week!

**Comment by Soreepeong** [comment]
It's now done! Since it's not thoroughly tested, it would be best for you to test the program before you get into a matched dungeon or something.
