### ISSUE TITLE
Option to hide the "stats" at the top

### ISSUE THREAD

**Issue by vekien** [Soreepeong/DPSViewer#2]
Very awesome tool, I really like it.

Would it be possible to add an option to hide the stats  at the top, this is the "FPS, Local time, Eorzean Time", etc. I personally don't have a use for these so it would be good to hide them.

Thank you!

**Comment by Soreepeong** [comment]
Hey there! I will do that, but I can't modify the program at the moment for a week; meanwhile, you can do dll->process()->wDPS.getChild(0)->visibility = 0; in the constructor of InGuiConfigWindow(?).cpp. 
Thank you for the interest, and please let me know if you'd like more features!

**Comment by Soreepeong** [comment]
It's now done!
